# Generated by Django 4.2.11 on 2025-12-29 15:21

from django.db import migrations, models
import sellers.models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='business_location',
            field=models.CharField(default='Nairobi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sellerdocument',
            name='document',
            field=models.FileField(upload_to=sellers.models.seller_document_path),
        ),
    ]
