# Generated by Django 4.2.11 on 2025-12-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketplaceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='verified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
